# The load balancer server configuration
server:
  bind: '0.0.0.0'
  port: '8080'
  maxconnections: '100'
  readTimeout: '100'
  writeTimeout: '100'
# The list of server you want to balance on
balancers: 'http://0.0.0.0:8081'
