# The load balancer server configuration
server:
  bind: 'localhost'
  port: '8080'
  maxconnections: '100'
  readTimeout: '30'
  writeTimeout: '30'
# The list of server you want to balance on
balancers: 'http://localhost:8081'
